name: Test G.h subsystem

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/stability_tests.yml
      - src/*
  pull_request:
    paths:
      - .github/workflows/stability_tests.yml
      - src/*
  workflow_dispatch:

env:
  UV_UNMANAGED_INSTALL: /usr/local/bin

jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Install Cython dependencies
        run: sudo apt update && sudo apt install -y gcc build-essential python3-dev curl

      - name: Install uv
        run: curl -fL --no-progress-meter --connect-timeout 15 --max-time 120 -- https://astral.sh/uv/install.sh | sh

      - name: Run tests
        run: uv run --group test -- pytest -v
